# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Dev environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlw-prod #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  # postfix: mlx
  location: canadacentral

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: sp-aml-github-prod # service principal name
  ado_service_connection_aml_ws: sp-aml-github-prod # service principal name

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: aml-github-prod
  aml_workspace: mlw-prod
  application_insights: mlwprod8502637901
  key_vault: mlwprod6321152617
  container_registry: crprod082423
  storage_account: mlwprod6943513838

  # For terraform reference
  # terraform_version: 0.14.7
  # terraform_workingdir: infrastructure
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_location: $(location)
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab
