
on:
  workflow_dispatch:

name: install-dependencies

jobs:

  install-azure-cli:
    runs-on: [self-hosted, windows, x64]
    steps:

    - name: Intall Azure CLI
      uses: elstudio/action-install-azure-cli@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

        