
on:
  workflow_dispatch:

name: install-dependencies

jobs:

  az-login:
    runs-on: [self-hosted, windows, x64]
    steps:       
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

        